name: Zip and Release
on:
  push:
    branches:
      - 'main'
    paths:
      - 'ModelingTools/**'
  workflow_dispatch:
jobs:
  zip_folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ModelingTools.zip ModelingTools
      - uses: actions/upload-artifact@v2
        with:
          name: ModelingTools
          path: ModelingTools.zip
          
  build_changelog:
      needs: zip_folder
      runs-on: ubuntu-latest
      steps:
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  release:
      needs: build_changelog
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
        - uses: actions/download-artifact@v2
          with:
            name: ModelingTools
            
        - uses: olegtarasov/get-tag@v2.1
          id: tagName
            
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ steps.tagName.outputs.tag }}
            body_path: ${{steps.build_changelog.outputs.changelog}}
            name:  ModelingTools
            files: ModelingTools.zip
